# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_content_type_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttypemap',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
